DemonSlayer(Kagaya).
DemonSlayer(Amane)
DemonSlayer(Hinaki).
DemonSlayer(Nichika).
DemonSlayer(Kiriya).
DemonSlayer(Kanata).
DemonSlayer(Giyu).
DemonSlayer(Mitsuri).
DemonSlayer(Obanai).
DemonSlayer(Sanemi).
DemonSlayer(Gyomei).
DemonSlayer(Muichiro).
DemonSlayer(Shinobu).
DemonSlayer(Kanae).
DemonSlayer(Sakonji).
DemonSlayer(Jigoro).
DemonSlayer(Kyojuro).
DemonSlayer(Shinjuro).
DemonSlayer(Tengen).
DemonSlayer(Kanao).
DemonSlayer(Tanjiro).
DemonSlayer(Zenitsu).
DemonSlayer(Inosuke).
DemonSlayer(Genya).
DemonSlayer(Murata).
DemonSlayer(Ozaki).
DemonSlayer(Aoi).
DemonSlayer(Sumi).
DemonSlayer(Kiyo).
DemonSlayer(Naho).
DemonSlayer(Goto).

Dead(Kagaya).
Dead(Amane).
Dead(Hinaki).
Dead(Nichika).
Dead(Mitsuri).
Dead(Obanai).
Dead(Gyomei).
Dead(Muichiro).
Dead(Shinobu).
Dead(Kyojuro).
Dead(Genya).

Alive(Kiriya).
Alive(kanata).
Alive(Giyu).
Alive(Sanemi).
Alive(kanae).
Alive(Sakonji).
Alive(Jigoro).
Alive(Shinjuro).
Alive(Tengen).
Alive(Kanao).
Alive(Tanjiro).
Alive(Zenitsu).
Alive(Inosuke).
Alive(Murata).
Alive(Ozaki).
Alive(Aoi).
Alive(Sumi).
Alive(Kiyo).
Alive(Naho).
Alive(Goto).    